apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cd-as-homework-admin
subjects:
  - kind: ServiceAccount
    name: cd
    namespace: homework
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io