apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-intro
  namespace: homework
spec:
  containers:
  - name: webserver
    image: nginx:1.14.2
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: files
      mountPath: /homework
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done; rm /homework/index.html"]
  initContainers:
  - name: init
    image: busybox:1.28
    command: ["/bin/sh", "-c", "touch /init/index.html"]
    volumeMounts:
    - name: files
      mountPath: /init
  volumes:
  - name: files
    emptyDir: {}