apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubernetes-volumes-pv
  namespace: homework
spec:
  storageClassName: kubernetes-volumes-storage
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"