apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernetes-volumes-pvc
  namespace: homework
spec:
  storageClassName: kubernetes-volumes-storage
  volumeName: kubernetes-volumes-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi