apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kubernetes-volumes-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate