apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.commonPath }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              name: {{ .Values.service.portName }}
      - path: {{ .Values.ingress.dataPath }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              name: {{ .Values.service.portName }}