apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  storageClassName: {{ .Values.storageClass.name }}
  capacity:
    storage: {{ .Values.pv.storage }}
  {{- with .Values.pv.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostPath:
    path: {{ .Values.pv.path }}