apiVersion: v2
name: kubernetes-templating
description: A Helm chart for Kubernetes
version: 0.1.0
dependencies:
  - name: postgresql
    version: 16.7.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled