apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-debug
  namespace: homework
spec:
  containers:
  - name: webserver
    image: kyos0109/nginx-distroless
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: files
      mountPath: /homework
    - name: nginx-conf
      mountPath: /etc/nginx/conf.d
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done; rm /homework/index.html"]
  initContainers:
  - name: init
    image: busybox:1.28
    command: ["/bin/sh", "-c", "echo '<!doctype html><title>kubernetes-intro</title>' > /init/index.html"]
    volumeMounts:
    - name: files
      mountPath: /init
  volumes:
  - name: files
    emptyDir: {}
  - name: nginx-conf
    configMap:
        name: nginx-conf