apiVersion: v1
kind: Service
metadata:
  name: kubernetes-monitoring-service
  namespace: homework
  labels: &labels
    app.kubernetes.io/name: kubernetes-monitoring
    app.kubernetes.io/instance: kubernetes-monitoring-instance
spec:
  selector: *labels
  ports:
    - name: http-k8s-mn-svc
      protocol: TCP
      port: 80
      targetPort: http-k8s-mn
    - name: nginx-metrics
      protocol: TCP
      port: 9113
      targetPort: nginx-metrics
  type: ClusterIP