apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-auth-secret-store
  namespace: vault
spec:
  provider:
    vault:
      server: "http://vault-server.vault.svc.cluster.local:8200"
      path: otus
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: otus
          serviceAccountRef:
            name: vault-auth
            namespace: vault