apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: otus-cred
  namespace: vault
spec:
  secretStoreRef:
    name: vault-auth-secret-store
    kind: SecretStore
  refreshInterval: 1m
  target:
    name: otus-cred
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: otus/cred
        property: username
    - secretKey: password
      remoteRef:
        key: otus/cred
        property: password