server:
  config: |
    disable_mlock = true 
    ui = true
    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
      cluster_address = "[::]:8201"
    }
    storage "consul" {
      path = "/bitnami/vault/data"
      address = "consul-headless.consul.svc.cluster.local:8500"
    }
    
    service_registration "kubernetes" {}